package main

import (
	"bytes"
	"encoding/json"
	"strings"
	"testing"
)

// runHelpDump executes the help-dump command in-process via newRootCmd(),
// capturing stdout, and returns the raw JSON bytes alongside the parsed dump.
func runHelpDump(t *testing.T) ([]byte, helpDump) {
	t.Helper()

	root := newRootCmd()
	var buf bytes.Buffer
	root.SetOut(&buf)
	root.SetErr(&buf)
	root.SetArgs([]string{"help-dump"})

	if err := root.Execute(); err != nil {
		t.Fatalf("help-dump execute failed: %v\noutput:\n%s", err, buf.String())
	}

	raw := buf.Bytes()
	var dump helpDump
	if err := json.Unmarshal(raw, &dump); err != nil {
		t.Fatalf("help-dump output is not valid JSON: %v\noutput:\n%s", err, raw)
	}
	return raw, dump
}

func TestHelpDump_Envelope(t *testing.T) {
	raw, dump := runHelpDump(t)

	if dump.Tool != "idea" {
		t.Errorf("tool = %q, want %q", dump.Tool, "idea")
	}
	if dump.SchemaVersion != 1 {
		t.Errorf("schema_version = %d, want 1", dump.SchemaVersion)
	}
	if dump.Version == "" {
		t.Error("version is empty, want the ldflags-stamped value (e.g. \"dev\")")
	}
	// The envelope MUST NOT emit captured_at: the capture timestamp is owned by
	// shll.ai's puller, not the tool (toolkit help-dump standard, "rule with
	// teeth"). Assert the field is absent from the raw JSON bytes.
	if strings.Contains(string(raw), "captured_at") {
		t.Errorf("help-dump envelope must not contain \"captured_at\", found it in raw JSON:\n%s", raw)
	}
}

func TestHelpDump_Root(t *testing.T) {
	_, dump := runHelpDump(t)

	if dump.Root.Name != "idea" {
		t.Errorf("root.name = %q, want %q", dump.Root.Name, "idea")
	}
	if dump.Root.Path != "idea" {
		t.Errorf("root.path = %q, want %q", dump.Root.Path, "idea")
	}
	if dump.Root.Short == "" {
		t.Error("root.short is empty")
	}
	if dump.Root.Usage == "" {
		t.Error("root.usage is empty")
	}
	if dump.Root.Text == "" {
		t.Error("root.text is empty")
	}
}

func TestHelpDump_FiltersAutoGeneratedAndHidden(t *testing.T) {
	_, dump := runHelpDump(t)

	excluded := []string{"completion", "help", "help-dump"}
	for _, name := range dump.commandNames() {
		for _, bad := range excluded {
			if name == bad {
				t.Errorf("root.commands must not contain %q (auto-generated or hidden)", bad)
			}
		}
	}
}

func TestHelpDump_RealSubcommandsPresent(t *testing.T) {
	_, dump := runHelpDump(t)

	// Each real user subcommand must be present with the correct full path.
	tests := []struct {
		name string
		path string
	}{
		{"add", "idea add"},
		{"list", "idea list"},
		{"show", "idea show"},
		{"done", "idea done"},
		{"reopen", "idea reopen"},
		{"edit", "idea edit"},
		{"rm", "idea rm"},
		{"prune", "idea prune"},
		{"fmt", "idea fmt"},
		{"update", "idea update"},
		{"shell-init", "idea shell-init"},
	}

	byName := make(map[string]helpNode, len(dump.Root.Commands))
	for _, c := range dump.Root.Commands {
		byName[c.Name] = c
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			node, ok := byName[tt.name]
			if !ok {
				t.Fatalf("root.commands missing subcommand %q", tt.name)
			}
			if node.Path != tt.path {
				t.Errorf("%s.path = %q, want %q", tt.name, node.Path, tt.path)
			}
		})
	}
}

func TestHelpDump_RepresentativeFieldsNonEmpty(t *testing.T) {
	_, dump := runHelpDump(t)

	var list *helpNode
	for i := range dump.Root.Commands {
		if dump.Root.Commands[i].Name == "list" {
			list = &dump.Root.Commands[i]
			break
		}
	}
	if list == nil {
		t.Fatal("expected a 'list' subcommand to assert representative fields against")
	}

	if list.Short == "" {
		t.Error("list.short is empty")
	}
	if list.Usage == "" {
		t.Error("list.usage is empty")
	}
	if list.Text == "" {
		t.Error("list.text is empty")
	}
	// text must reproduce -h: description, blank line, then the Usage: block.
	if !strings.Contains(list.Text, "Usage:") {
		t.Errorf("list.text should contain a Usage: block, got:\n%s", list.Text)
	}
}

func TestHelpDump_LeafCommandsSerializeEmptyArray(t *testing.T) {
	raw, dump := runHelpDump(t)

	// At least one real leaf exists; assert none serialize commands as null.
	if strings.Contains(string(raw), "\"commands\": null") {
		t.Error("leaf nodes must serialize commands as [], found \"commands\": null in raw JSON")
	}
	if !strings.Contains(string(raw), "\"commands\": []") {
		t.Error("expected at least one leaf with \"commands\": [] in raw JSON")
	}

	// And on the parsed side, leaves must be non-nil empty slices.
	for _, c := range dump.Root.Commands {
		if c.Commands == nil {
			t.Errorf("subcommand %q has nil commands; want non-nil empty slice", c.Name)
		}
	}
}

func TestHelpDump_TextContainsDefaultFlags(t *testing.T) {
	_, dump := runHelpDump(t)

	// Cobra registers the default help/version flags lazily during Execute().
	// help-dump walks child commands without executing them, so buildNode must
	// init those flags itself for UsageString() to render them. Lock the
	// contract: the root's Flags block carries both -h and -v; every leaf's
	// Flags block carries -h. These lines are part of the byte-for-byte -h
	// output the frozen wt.json contract requires.

	// Root: both --help and --version (root has Version set).
	for _, want := range []string{"-h, --help", "-v, --version"} {
		if !strings.Contains(dump.Root.Text, want) {
			t.Errorf("root.text Flags block missing %q, got:\n%s", want, dump.Root.Text)
		}
	}

	// Representative leaf (list): must carry -h, --help. Subcommands have no
	// Version, so -v, --version must NOT appear.
	var list *helpNode
	for i := range dump.Root.Commands {
		if dump.Root.Commands[i].Name == "list" {
			list = &dump.Root.Commands[i]
			break
		}
	}
	if list == nil {
		t.Fatal("expected a 'list' subcommand to assert default flags against")
	}
	if !strings.Contains(list.Text, "-h, --help") {
		t.Errorf("list.text Flags block missing %q, got:\n%s", "-h, --help", list.Text)
	}
	if strings.Contains(list.Text, "-v, --version") {
		t.Errorf("list.text must not contain %q (subcommands have no Version), got:\n%s", "-v, --version", list.Text)
	}
}

// commandNames returns the names of the root's direct subcommands.
func (d helpDump) commandNames() []string {
	names := make([]string, 0, len(d.Root.Commands))
	for _, c := range d.Root.Commands {
		names = append(names, c.Name)
	}
	return names
}
