package main

import (
	"fmt"
	"io"

	"github.com/spf13/cobra"
)

// shellListForError is the list advertised in argument-validation errors.
// The brief specifies "Supported: zsh, bash" verbatim; fish and powershell
// still work if requested explicitly but aren't surfaced in the error text
// to keep the suggestion focused on the common case.
const shellListForError = "zsh, bash"

func newShellInitCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "shell-init <shell>",
		Short: "Emit shell-eval-safe completion snippet for the given shell",
		Long: `Emit a shell-eval-safe completion snippet for the given shell.

Intended to be wired into shell rc files via:

  echo 'eval "$(idea shell-init zsh)"' >> ~/.zshrc
  echo 'eval "$(idea shell-init bash)"' >> ~/.bashrc

Unlike "idea completion <shell>", the output is wrapped with a banner comment
and (for zsh) lazy-loads compinit so the snippet is safe to drop into an rc
file even before the user has initialised the completion system. The
underlying completion function is generated by cobra and is identical in
behavior to "idea completion <shell>".

Supported shells: zsh, bash, fish, powershell.`,
		// We do our own arg validation so we can emit the exact error text
		// (and exit code 2) that the shll meta-CLI expects.
		Args:          cobra.ArbitraryArgs,
		SilenceUsage:  true,
		SilenceErrors: true,
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				fmt.Fprintf(cmd.ErrOrStderr(), "idea shell-init: missing shell. Supported: %s\n", shellListForError)
				return &usageError{errSilent}
			}
			shell := args[0]
			out := cmd.OutOrStdout()
			root := cmd.Root()

			switch shell {
			case "zsh":
				return emitZsh(root, out)
			case "bash":
				return emitBash(root, out)
			case "fish":
				return emitFish(root, out)
			case "powershell":
				return emitPowerShell(root, out)
			default:
				fmt.Fprintf(cmd.ErrOrStderr(), "idea shell-init: unsupported shell '%s'. Supported: %s\n", shell, shellListForError)
				return &usageError{errSilent}
			}
		},
	}
	return cmd
}

func emitZsh(root *cobra.Command, out io.Writer) error {
	banner := `# idea(1) zsh completion
# Install:
#   echo 'eval "$(idea shell-init zsh)"' >> ~/.zshrc
#
# This snippet is intended for ` + "`eval`" + `, not for autoload via $fpath. It defines
# the _idea function and registers it with ` + "`compdef`" + `. compinit is loaded lazily
# if the user hasn't already done so, since ` + "`compdef`" + ` is unavailable until then.

# Lazy-load compinit if the user hasn't already initialised the completion
# system — ` + "`compdef`" + ` is provided by compinit and is required by the cobra-
# generated snippet below to register _idea against the ` + "`idea`" + ` command.
(( $+functions[compdef] )) || { autoload -Uz compinit && compinit -i }

`
	if _, err := fmt.Fprint(out, banner); err != nil {
		return err
	}
	return root.GenZshCompletion(out)
}

func emitBash(root *cobra.Command, out io.Writer) error {
	banner := `# idea(1) bash completion
# Install:
#   echo 'eval "$(idea shell-init bash)"' >> ~/.bashrc
#
# This snippet is intended for ` + "`eval`" + `, not for autoload via a completions
# directory. The cobra-generated function below registers itself with
# ` + "`complete -F`" + ` at source time.

`
	if _, err := fmt.Fprint(out, banner); err != nil {
		return err
	}
	return root.GenBashCompletionV2(out, true)
}

func emitFish(root *cobra.Command, out io.Writer) error {
	banner := `# idea(1) fish completion
# Install:
#   idea shell-init fish | source
# Or, for persistent setup:
#   idea shell-init fish > ~/.config/fish/completions/idea.fish

`
	if _, err := fmt.Fprint(out, banner); err != nil {
		return err
	}
	return root.GenFishCompletion(out, true)
}

func emitPowerShell(root *cobra.Command, out io.Writer) error {
	banner := `# idea(1) powershell completion
# Install (add to $PROFILE):
#   idea shell-init powershell | Out-String | Invoke-Expression

`
	if _, err := fmt.Fprint(out, banner); err != nil {
		return err
	}
	return root.GenPowerShellCompletionWithDesc(out)
}
