package main

import (
	"bytes"
	"os/exec"
	"strings"
	"testing"
)

// TestShellInit_ZshHasBannerAndCompletion verifies the zsh snippet starts
// with the install banner and includes the cobra-generated completion body.
func TestShellInit_ZshHasBannerAndCompletion(t *testing.T) {
	bin := buildBinary(t)

	// Intentionally run with no working directory pinned to a git repo —
	// shell-init must work outside any git repo so users can stick the eval
	// in their rc file unconditionally.
	cmd := exec.Command(bin, "shell-init", "zsh")
	cmd.Dir = t.TempDir()
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("shell-init zsh failed: %v\n%s", err, out)
	}

	s := string(out)
	wantSubstrings := []string{
		"# idea(1) zsh completion",
		`echo 'eval "$(idea shell-init zsh)"' >> ~/.zshrc`,
		"intended for `eval`",
		"compinit",
		"compdef _idea idea",
		"_idea()",
	}
	for _, want := range wantSubstrings {
		if !strings.Contains(s, want) {
			t.Errorf("zsh output missing %q\n--- output ---\n%s", want, s)
		}
	}
}

// TestShellInit_BashHasBannerAndCompletion verifies the bash snippet.
func TestShellInit_BashHasBannerAndCompletion(t *testing.T) {
	bin := buildBinary(t)

	cmd := exec.Command(bin, "shell-init", "bash")
	cmd.Dir = t.TempDir()
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("shell-init bash failed: %v\n%s", err, out)
	}

	s := string(out)
	wantSubstrings := []string{
		"# idea(1) bash completion",
		`echo 'eval "$(idea shell-init bash)"' >> ~/.bashrc`,
		"__start_idea",
	}
	for _, want := range wantSubstrings {
		if !strings.Contains(s, want) {
			t.Errorf("bash output missing %q\n--- output ---\n%s", want, s)
		}
	}
}

// TestShellInit_MissingShellExitsTwo verifies the no-arg error path.
func TestShellInit_MissingShellExitsTwo(t *testing.T) {
	bin := buildBinary(t)

	cmd := exec.Command(bin, "shell-init")
	cmd.Dir = t.TempDir()
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	err := cmd.Run()
	if err == nil {
		t.Fatalf("expected non-zero exit for missing shell arg")
	}
	exitErr, ok := err.(*exec.ExitError)
	if !ok {
		t.Fatalf("expected *exec.ExitError, got %T: %v", err, err)
	}
	if got := exitErr.ExitCode(); got != 2 {
		t.Errorf("expected exit code 2, got %d", got)
	}
	wantMsg := "idea shell-init: missing shell. Supported: zsh, bash"
	if !strings.Contains(stderr.String(), wantMsg) {
		t.Errorf("expected stderr to contain %q, got: %s", wantMsg, stderr.String())
	}
}

// TestShellInit_UnsupportedShellExitsTwo verifies the unknown-shell error path.
func TestShellInit_UnsupportedShellExitsTwo(t *testing.T) {
	bin := buildBinary(t)

	cmd := exec.Command(bin, "shell-init", "wsh")
	cmd.Dir = t.TempDir()
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	err := cmd.Run()
	if err == nil {
		t.Fatalf("expected non-zero exit for unsupported shell")
	}
	exitErr, ok := err.(*exec.ExitError)
	if !ok {
		t.Fatalf("expected *exec.ExitError, got %T: %v", err, err)
	}
	if got := exitErr.ExitCode(); got != 2 {
		t.Errorf("expected exit code 2, got %d", got)
	}
	wantMsg := "idea shell-init: unsupported shell 'wsh'. Supported: zsh, bash"
	if !strings.Contains(stderr.String(), wantMsg) {
		t.Errorf("expected stderr to contain %q, got: %s", wantMsg, stderr.String())
	}
}

// TestShellInit_CompletionSubcommandStillExists guards against accidentally
// removing or shadowing the cobra-autogenerated `completion` subcommand.
func TestShellInit_CompletionSubcommandStillExists(t *testing.T) {
	bin := buildBinary(t)

	cmd := exec.Command(bin, "completion", "zsh")
	cmd.Dir = t.TempDir()
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("completion zsh failed (it should still exist alongside shell-init): %v\n%s", err, out)
	}
	if !strings.Contains(string(out), "compdef _idea idea") {
		t.Errorf("expected legacy `completion zsh` to still emit cobra completion, got: %s", out)
	}
}
